name: 🚀 Test And Build

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:
    name: 🎉 Test and Build
    runs-on: ubuntu-latest 
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      
      - name: 🤖 Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: 📂 Install Dependencies
        run: |
          npm i
      
      - name: 🥳 Run All Tests
        run: |
          npm run test

      - name: 🔨 Build Project
        run: |
          npm run build
